// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAv77wybIPYtAb3rILWSuP3yiAhCmlqRps',
    appId: '1:181529049167:web:4ae13f47473752e852923a',
    messagingSenderId: '181529049167',
    projectId: 'safehavenw',
    authDomain: 'safehavenw.firebaseapp.com',
    storageBucket: 'safehavenw.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDS1nfsuZF5Ut54O-qT-ZGTZPNSrwBi_AU',
    appId: '1:181529049167:android:a740dfeaba0bb2f552923a',
    messagingSenderId: '181529049167',
    projectId: 'safehavenw',
    storageBucket: 'safehavenw.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBsYBlJKoJwGtMQyOOUer6KKahqeRMDUho',
    appId: '1:181529049167:ios:464821d5a12ac23952923a',
    messagingSenderId: '181529049167',
    projectId: 'safehavenw',
    storageBucket: 'safehavenw.firebasestorage.app',
    iosBundleId: 'com.example.safehaven',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBsYBlJKoJwGtMQyOOUer6KKahqeRMDUho',
    appId: '1:181529049167:ios:464821d5a12ac23952923a',
    messagingSenderId: '181529049167',
    projectId: 'safehavenw',
    storageBucket: 'safehavenw.firebasestorage.app',
    iosBundleId: 'com.example.safehaven',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAv77wybIPYtAb3rILWSuP3yiAhCmlqRps',
    appId: '1:181529049167:web:29d805191cf051ae52923a',
    messagingSenderId: '181529049167',
    projectId: 'safehavenw',
    authDomain: 'safehavenw.firebaseapp.com',
    storageBucket: 'safehavenw.firebasestorage.app',
  );
}
